services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  postgres:
    container_name: "postgres"
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "-c wal_level=logical"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "postgres"
    volumes:
    - "airbnb_pg_data:/var/lib/postgresql/data"
    ports:
    - target: 5432
      published: 5435
    restart: unless-stopped
  kafka:
    container_name: "kafka"
    image: "docker.io/confluentinc/confluent-local:8.1.1"
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://localhost:29092,CONTROLLER://localhost:29093,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092,PLAINTEXT_INTERNAL://kafka:9093"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "kafka"
    volumes:
    - "airbnb_kafka_data:/var/lib/kafka/data"
    ports:
    - target: 9092
      published: 9092
    - target: 9093
      published: 9093
    restart: unless-stopped
  rabbit:
    container_name: "rabbit"
    image: "docker.io/library/rabbitmq:4.2-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "bByrGNVzrTYcs!KU9I3Dve"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "rabbit"
    volumes:
    - "airbnb_rabbit_data:/var/lib/rabbitmq"
    ports:
    - target: 5672
      published: 5672
    - target: 15672
      published: 15672
    restart: unless-stopped
  elasticsearch:
    container_name: "elasticsearch"
    image: "docker.io/library/elasticsearch:8.17.3"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "qCMpJy58V8IS0Lbt2TfuqG"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "elasticsearch"
    volumes:
    - "airbnb_es_data:/usr/share/elasticsearch/data"
    ports:
    - target: 9200
      published: 9200
    - target: 9300
      published: 9300
    restart: unless-stopped
  redis:
    container_name: "redis"
    image: "docker.io/library/redis:8.6"
    environment:
      REDIS_PASSWORD: "FVRtZScpLshy4w9ZIJXwgi"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "redis"
    volumes:
    - "airbnb_redis_data:/data"
    ports:
    - target: 6379
      published: 6379
    command:
    - "-c"
    - "redis-server --requirepass $REDIS_PASSWORD --save 60 1"
    - "/bin/sh"
    restart: unless-stopped
  debezium:
    container_name: "debezium"
    image: "docker.io/debezium/connect:2.5"
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      JAVA_OPTS: "-Xms128m -Xmx128m"
      ConnectionStrings__postgres: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5435"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      POSTGRES_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435"
      POSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435"
      ConnectionStrings__kafka: "kafka:9092"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "debezium"
    ports:
    - target: 8083
      published: 8083
    restart: unless-stopped
  debezium-configurator:
    container_name: "debezium-configurator"
    image: "debezium-configurator:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      DEBEZIUM_HTTP: "http://debezium:8083"
      services__debezium__http__0: "http://debezium:8083"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "debezium-configurator"
    restart: unless-stopped
  userservice:
    container_name: "userservice"
    image: "userservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__userdb: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T;Database=userdb"
      USERDB_HOST: "postgres"
      USERDB_PORT: "5435"
      USERDB_USERNAME: "postgres"
      USERDB_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      USERDB_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435/userdb"
      USERDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435/userdb"
      USERDB_DATABASENAME: "userdb"
      ConnectionStrings__rabbit: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "bByrGNVzrTYcs!KU9I3Dve"
      RABBIT_URI: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "userservice"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  propertyservice:
    container_name: "propertyservice"
    image: "propertyservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__propdb: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T;Database=propdb"
      PROPDB_HOST: "postgres"
      PROPDB_PORT: "5435"
      PROPDB_USERNAME: "postgres"
      PROPDB_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      PROPDB_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435/propdb"
      PROPDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435/propdb"
      PROPDB_DATABASENAME: "propdb"
      ConnectionStrings__rabbit: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "bByrGNVzrTYcs!KU9I3Dve"
      RABBIT_URI: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "propertyservice"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  bookingservice:
    container_name: "bookingservice"
    image: "bookingservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__bookdb: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T;Database=bookdb"
      BOOKDB_HOST: "postgres"
      BOOKDB_PORT: "5435"
      BOOKDB_USERNAME: "postgres"
      BOOKDB_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      BOOKDB_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435/bookdb"
      BOOKDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435/bookdb"
      BOOKDB_DATABASENAME: "bookdb"
      ConnectionStrings__rabbit: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "bByrGNVzrTYcs!KU9I3Dve"
      RABBIT_URI: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      ConnectionStrings__kafka: "kafka:9092"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "bookingservice"
    ports:
    - target: 8080
      published: 10004
    - target: 8443
      published: 10005
    restart: unless-stopped
  paymentservice:
    container_name: "paymentservice"
    image: "paymentservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__paydb: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T;Database=paydb"
      PAYDB_HOST: "postgres"
      PAYDB_PORT: "5435"
      PAYDB_USERNAME: "postgres"
      PAYDB_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      PAYDB_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435/paydb"
      PAYDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435/paydb"
      PAYDB_DATABASENAME: "paydb"
      ConnectionStrings__rabbit: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "bByrGNVzrTYcs!KU9I3Dve"
      RABBIT_URI: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "paymentservice"
    ports:
    - target: 8080
      published: 10006
    - target: 8443
      published: 10007
    restart: unless-stopped
  searchservice:
    container_name: "searchservice"
    image: "searchservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__elasticsearch: "http://elastic:qCMpJy58V8IS0Lbt2TfuqG@elasticsearch:9200"
      ConnectionStrings__kafka: "kafka:9092"
      KAFKA_HOST: "kafka"
      KAFKA_PORT: "9092"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "searchservice"
    ports:
    - target: 8080
      published: 10008
    - target: 8443
      published: 10009
    restart: unless-stopped
  chatservice:
    container_name: "chatservice"
    image: "chatservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      ConnectionStrings__chatdb: "Host=postgres;Port=5435;Username=postgres;Password=FZUUVsp9ojf2oz!ZxUTW7T;Database=chatdb"
      CHATDB_HOST: "postgres"
      CHATDB_PORT: "5435"
      CHATDB_USERNAME: "postgres"
      CHATDB_PASSWORD: "FZUUVsp9ojf2oz!ZxUTW7T"
      CHATDB_URI: "postgresql://postgres:{postgres-password-uri-encoded.value}@postgres:5435/chatdb"
      CHATDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5435/chatdb"
      CHATDB_DATABASENAME: "chatdb"
      ConnectionStrings__rabbit: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "bByrGNVzrTYcs!KU9I3Dve"
      RABBIT_URI: "amqp://guest:{rabbit-password-uri-encoded.value}@rabbit:5672"
      ConnectionStrings__redis: "redis:6379,password=FVRtZScpLshy4w9ZIJXwgi"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "FVRtZScpLshy4w9ZIJXwgi"
      REDIS_URI: "http://:{redis-password-uri-encoded.value}@redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "chatservice"
    ports:
    - target: 8080
      published: 10010
    - target: 8443
      published: 10011
    restart: unless-stopped
  gateway:
    container_name: "gateway"
    image: "gateway:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      DOTNET_gcServer: "0"
      USERSERVICE_HTTP: "http://userservice:8080"
      services__userservice__http__0: "http://userservice:8080"
      PROPERTYSERVICE_HTTP: "http://propertyservice:8080"
      services__propertyservice__http__0: "http://propertyservice:8080"
      BOOKINGSERVICE_HTTP: "http://bookingservice:8080"
      services__bookingservice__http__0: "http://bookingservice:8080"
      PAYMENTSERVICE_HTTP: "http://paymentservice:8080"
      services__paymentservice__http__0: "http://paymentservice:8080"
      SEARCHSERVICE_HTTP: "http://searchservice:8080"
      services__searchservice__http__0: "http://searchservice:8080"
      CHATSERVICE_HTTP: "http://chatservice:8080"
      services__chatservice__http__0: "http://chatservice:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "gateway"
    ports:
    - target: 8080
      published: 10012
    - target: 8443
      published: 10013
    restart: unless-stopped
volumes:
  airbnb_pg_data: {}
  airbnb_kafka_data: {}
  airbnb_rabbit_data: {}
  airbnb_es_data: {}
  airbnb_redis_data: {}
