// <auto-generated />
using System;
using System.Collections.Generic;
using Airbnb.PropertyService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airbnb.PropertyService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504035848_AddMissingTablesAndSeedData")]
    partial class AddMissingTablesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.AdminDivision", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NameLocal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode");

                    b.HasIndex("CountryCode", "Level");

                    b.ToTable("admin_divisions", (string)null);
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IconCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Category = "Connectivity",
                            IconCode = "wifi",
                            Name = "High-speed Wi-Fi"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Category = "Entertainment",
                            IconCode = "tv",
                            Name = "HD TV with Netflix"
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            Category = "Outdoor",
                            IconCode = "pool",
                            Name = "Private Pool"
                        },
                        new
                        {
                            Id = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            Category = "Cooking",
                            IconCode = "kitchen",
                            Name = "Fully Equipped Kitchen"
                        },
                        new
                        {
                            Id = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            Category = "Facilities",
                            IconCode = "parking",
                            Name = "Free Parking"
                        },
                        new
                        {
                            Id = new Guid("f6f6f6f6-f6f6-f6f6-f6f6-f6f6f6f6f6f6"),
                            Category = "Comfort",
                            IconCode = "ac",
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = new Guid("07070707-0707-0707-0707-070707070707"),
                            Category = "Facilities",
                            IconCode = "washer",
                            Name = "Washing Machine"
                        },
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            Category = "Facilities",
                            IconCode = "gym",
                            Name = "Gym Access"
                        });
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PropertyId", "AmenityId");

                    b.ToTable("property_amenities", (string)null);
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId", "Type");

                    b.ToTable("property_images", (string)null);
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Admin1Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Admin2Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("DisplayAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CountryCode", "Admin1Code", "Admin2Code");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.AdminDivision", b =>
                {
                    b.HasOne("Airbnb.PropertyService.Domain.Entities.AdminDivision", null)
                        .WithMany()
                        .HasForeignKey("ParentCode");
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.PropertyAmenity", b =>
                {
                    b.HasOne("Airbnb.PropertyService.Domain.Property", null)
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("Airbnb.PropertyService.Domain.Property", null)
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Property", b =>
                {
                    b.OwnsOne("Airbnb.PropertyService.Domain.ValueObjects.AddressRaw", "AddressRaw", b1 =>
                        {
                            b1.Property<Guid>("PropertyId");

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("StreetAddress")
                                .IsRequired();

                            b1.Property<Dictionary<string, string>>("SubDivisions");

                            b1.Property<string>("Unit");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1
                                .ToJson("AddressRaw")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");

                            b1.OwnsOne("Airbnb.PropertyService.Domain.ValueObjects.AddressNotes", "Notes", b2 =>
                                {
                                    b2.Property<Guid>("AddressRawPropertyId");

                                    b2.Property<string>("Internal");

                                    b2.Property<string>("Public");

                                    b2.HasKey("AddressRawPropertyId");

                                    b2.ToTable("properties");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressRawPropertyId");
                                });

                            b1.Navigation("Notes");
                        });

                    b.OwnsOne("Airbnb.PropertyService.Domain.ValueObjects.HouseRules", "HouseRules", b1 =>
                        {
                            b1.Property<Guid>("PropertyId");

                            b1.Property<bool>("AllowEvents");

                            b1.Property<bool>("AllowPets");

                            b1.Property<bool>("AllowSmoking");

                            b1.Property<TimeOnly>("CheckInTime");

                            b1.Property<TimeOnly>("CheckOutTime");

                            b1.Property<bool>("FlexibleCheckIn");

                            b1.Property<bool>("FlexibleCheckOut");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1
                                .ToJson("HouseRules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Airbnb.PropertyService.Domain.ValueObjects.Pricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("PropertyId");

                            b1.Property<decimal>("BasePrice");

                            b1.Property<decimal>("CleaningFee");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3);

                            b1.Property<decimal>("ServiceFee");

                            b1.Property<decimal>("WeekendPremiumPercent");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1
                                .ToJson("Pricing")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Airbnb.PropertyService.Domain.ValueObjects.PropertyCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("PropertyId");

                            b1.Property<int>("BathroomCount");

                            b1.Property<int>("BedCount");

                            b1.Property<int>("BedroomCount");

                            b1.Property<int>("GuestCount");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1
                                .ToJson("Capacity")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("AddressRaw")
                        .IsRequired();

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("HouseRules")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("Airbnb.PropertyService.Domain.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PropertyAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
